<?php

namespace AppBundle\Repository;

/**
 * TypeCoordonneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCoordonneeRepository extends \Doctrine\ORM\EntityRepository
{
}
